site_name: KitPvP Plus Documentation
site_url: https://wiki.nucker.me
repo_url: https://github.com/Nuckerr/KitPvPPlus-docs
repo_name: Nuckerr/KitPvPPlus-docs
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  language: en
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    - scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: cyan
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
